version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: "on-failure"
    logging:
      options:
        max-size: "3m"
        max-file: "2"
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tach

  mongo:
    image: mongo:7
    container_name: mongo
    logging:
      options:
        max-size: "3m"
        max-file: "2"
    restart: "on-failure"
    env_file:
      - .env
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - tach_mongo_data:/data/db
    # prevent logs
    command: mongod --quiet --logpath /dev/null
    networks:
      - tach

volumes:
  tach_mongo_data:

networks:
  tach:
    name: tach
